### PR TITLE
Easy text adjustments

### LINKED ISSUE #19: Easy theme adjustments
`easy_font_size()`
`easy_font_colour()`
`easy_font()` (a.k.a. family; may not actually be easy)

as well as anything else that requires `theme(foo = element_bar(zap = ""))` to work.

FYI, size, colour, etc... should be able to be added via `easy_rotate_*_labels()` if #18 is fixed.

### LINKED ISSUE #24: support legend titles in easy_labs
As per

https://twitter.com/nnstats/status/1093351450476990464

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">tbh the way they could really get me is by asking me to change a legend title in ggplot without google, I&#39;d have to quit on the spot</p>&mdash; Namita (@nnstats) <a href="https://twitter.com/nnstats/status/1093351450476990464?ref_src=twsrc%5Etfw">February 7, 2019</a></blockquote>

### LINKED ISSUE #28: Increase font size of everything
> Increasing the font size of everything at once.

-- https://twitter.com/bhive01/status/1202418127029432320?s=20

@bhive01

### PR DESCRIPTION
**Pull request by jonocarroll**
Text attribute adjustment:

* `easy_change_text()` which takes a theme element (choices: `text, axis.text, axis.text.x, axis.text.y, axis.title, axis.title.x, axis.title.y, legend.text, legend.title, plot.title, plot.subtitle, plot.caption, strip.text, strip.text.x, strip.text.y`) and a theme attribute (choices: `size, family, face, colour, hjust, vjust, angle, lineheight, color, margin`) and a value to set.

Common (?) use-case shortcuts:

* `easy_all_text_color()`
* `easy_all_text_colour()`
* `easy_text_size()`
* `easy_all_text_size()`
* `easy_change_text()`
* `easy_plot_caption_size()`
* `easy_plot_legend_size()`
* `easy_plot_legend_title_size()`
* `easy_plot_subtitle_size()`
* `easy_plot_title_size()`
* `easy_x_axis_labels_size()`
* `easy_x_axis_title_size()`
* `easy_y_axis_labels_size()`
* `easy_y_axis_title_size()`

<br />

- [x] `teach` options (not specific to the called function)
- [x] tests
- [x] closes #19 
- [x] closes #24 
- [x] closes #28 

Any other suggestions @bhive01?

### CODE REVIEW

**Comment by bhive01** [comment]
I'm sorry I didn't respond to your initial posting. What I was thinking about on Twitter was when I'm prepping a figure for a presentation and I just want to bump up the base_size so that everything gets bigger together. At least I think that's how it works, every time I try and do it I have to look it up. I think it's base_size that way everything else scales from there. I've looked very briefly here: https://github.com/jonocarroll/ggeasy/blob/feature/text_size/R/text.R and it didn't look like you were using base size, but perhaps you've got it covered with rel or something?

**Comment by jonocarroll** [comment]
This PR lets you set the size for each component (or all of them) explicitly. It looks like `base_size = 11` for most themes. I could add a shortcut to modify `base_size` if you think there's some relative scaling involved.

**Comment by jonocarroll** [comment]
For `p1 <- ggplot(mtcars, aes(hp, mpg)) + geom_point()`,

`p1 + theme_grey(base_size = 15)`

and 

`p1 + theme_grey() + easy_change_text(c("text", "title"), "size", 15)`

appear to give the same results visually, with some odd scaling happening.

I can work on getting my functions to be more consistent with that output.

**Comment by jonocarroll** [comment]
It looks like the `theme_*` functions accept a `base_size` argument then pass that on to the individual components (with various `rel` components). That means it doesn't generalise outside of an individual theme. The implementation I have will allow you to specify some or all of the specific sizes.

**Comment by jonocarroll** [comment]
Ready to merge but I'll let it steep for a few days. Feel free to comment if you spot anything.

@bhive01 @yonicd

**Pull request merged**
