### PR TITLE
Cleanup/sept18

### PR DESCRIPTION
**Pull request by jonocarroll**
I've finally found some time to work on this, sorry for the long wait. I've added some more tests (100% coverage on all but the ticks-text)

* I improved the axes rotation code and added helpers for both x and y
* All functions now use a `teach` argument which is also tested to be correct
* I merged @yonicd's labs update but re-wrote part of it - please confirm it works as expected
* moar tests, including some `vdiffr` ones
* updated test coverage using `covrpage`
* built `pkgdown` site

Feel free to add any comments/suggestions. I think we can submit to CRAN once the last of the functions are how we want them.

### CODE REVIEW

**Comment by AliciaSchep** [comment]
LGTM!  I think a cran release in near future makes sense... one thing I noticed though is that the vignette uses patchwork, which I don't think is on CRAN yet. I think the package can't suggest a GH-only package (but maybe I'm wrong about that). And I got an error, warning, notes on R Cmd Check on my system, but likely stuff that can be sorted out pretty quick...

**Comment by jonocarroll** [comment]
Cheers! I overlooked the `patchwork` thing but it's not critical; we can just as easily inline all of the vignette plots or use `cowplot`.

I'll address the `R CMD check` issues once we're happy with the functionality/as we're going.

Are there any other on-brand 'simple' helpers we'd like to add before submitting?

**Comment by yonicd** [comment]
i like the teach part, but you gutted easy_labs and the examples dont work properly. I think you should restore the code that worked and add the teach attr to it.

**Comment by yonicd** [comment]
which test is failing? Is it because the new image is different than the benchmark?

**Comment by jonocarroll** [comment]
No, it was some `expect_equal(x, x)` in `test-labs`. The "x-axis" label was not being updated by the `ggeasy` route and the test was ignoring it by only comparing to itself. The other failing test was for the title, IIRC.

**Comment by yonicd** [comment]
i pulled the current commit of the branch. I am getting this message on skipped tests for the doppleganger, other than that all passed.

```r
test-labs.R:30: skip: easy_labs uses column attrib
Failed doppelganger was generated with a newer FreeType version.
Please install FreeType 2.9 on your system

test-labs.R:41: skip: regular labs overides easy_labs 
Failed doppelganger was generated with a newer FreeType version.
Please install FreeType 2.9 on your system

test-labs.R:52: skip: regular labs pass new labels through easy_labs 
Failed doppelganger was generated with a newer FreeType version.
Please install FreeType 2.9 on your system

test-labs.R:71: skip: column name used when no column attrib present
Failed doppelganger was generated with a newer FreeType version.
Please install FreeType 2.9 on your system
```

**Comment by jonocarroll** [comment]
I've just pulled (no changes), installed (newest libraries), and re-built, and I get

```
Error: Test failed: 'regular labs overides easy_labs '
* easy_res$labels[sort(names(easy_res$labels))] not equal to hard_res$labels[sort(names(hard_res$labels))].
Component “x”: 1 string mismatch

Error: Test failed: 'regular labs pass new labels through easy_labs '
* easy_res$labels[sort(names(easy_res$labels))] not equal to hard_res$labels[sort(names(hard_res$labels))].
Names: 2 string mismatches
Length mismatch: comparison on first 3 components
Component 2: 1 string mismatch
Component 3: 1 string mismatch
```

On inspection, the "x-axis" and "my title" labels are not showing up in the plots for `easy_res`. I'm having a difficult time parsing your implementation, which was one of the reasons for me having a try. Rolling back to 9ae6ebbdce543a0978c98be45e5c0949ebd4b69f and re-building, the easy-vs-easy problem is still there, but both `easy_res` and `hard_res` _do_ produce identical output. 

My preference would still be towards patching my implementation for the couple of examples which you noticed did not pass. Re-running these again, it looks like the sole failure is in 

```r
# easy_labs does let you build ggplots with columns
# that inherit the attribute 'labels'
p1 + easy_labs()
```

which I'm sure I can repair.

**Pull request merged**
