### PR TITLE
Easy remove gridlines

### PR DESCRIPTION
**Pull request by thomas-neitmann**
Easily remove grid lines, as discussed in #31.

### CODE REVIEW

**Comment by jonocarroll** [comment]
Thank you! I'll work through the changes soon. I like the idea of abstracting out the `teach` argument but I want to carefully check some edge-cases.

**Comment by jonocarroll** [comment]
Sorry, I got distracted from this but I'm having a closer look now. I have some suggestions I'm going to try to push to your branch.

Also, FYI, 
```
Warning message:
`ctxt_frame()` is deprecated as of rlang 0.3.0.
```

**Comment by thomas-neitmann** [comment]
Thanks a lot for merging into master @jonocarroll!

In the meantime I thought of a slightly different interface for the functions. What do you think of
```r
easy_remove_gridlines <- function(which = "XYxy")
easy_remove_x_gridlines <- function(which = "Xx")
easy_remove_y_gridlines <- function(which = "Yy")
```
Upper and lowercase letters would indicate major and minor gridlines, respectively. I've implement it like this for the themes in `{ggcharts}` [here](https://github.com/thomas-neitmann/ggcharts/blob/master/R/theme.R#L334).

I feel this is a much cleaner and easier to use interface. What do you think?

**Comment by jonocarroll** [comment]
I've been meaning to merge this for far too long. Thank you again for the contribution!

**Pull request merged**
