### PR TITLE
Easy center title

### PR DESCRIPTION
**Pull request by thomas-neitmann**
A function to easily center-align the plot title as described in #33.

### CODE REVIEW

**Comment by jonocarroll** [comment]
Cheers, this looks great, and reminded me of a feature I should add... https://github.com/jonocarroll/ggeasy/blob/feature/plot.title.position/R/text.R#L218-L246

Could you please add yourself to `DESCRIPTION` as a contributor (`ctb`)?

**Comment by thomas-neitmann** [comment]
Done 🙂

**Comment by jonocarroll** [comment]
Thank you!

**Comment by thomas-neitmann** [comment]
My pleasure 😄
Thank you for creating `ggeasy`! I think you really hit a nerve with this package. I am a seasoned `ggplot2` user but every time I need to change something on a theme I need to look up the documentation and that gives me the shivers. There's just so many...

**Pull request merged**
